server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true

spring:
  application:
    name: ui-thymeleaf-app
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
  session:
    store-type: none