server:
  port: 9090

spring:

  quartz:
    overwrite-existing-jobs: true
    auto-startup: true
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          threadPool:
            threadCount: 5

  datasource:
    url: jdbc:postgresql://postgres:5432/backendbootstrapdb
    username: backend-bootstrap-user
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: create.sql
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false

  data:
    mongodb:
      authentication-database: admin
      username: backend-bootstrap-user
      password: password
      database: backendbootstrapdb
      host: mongo
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
    eureka-server-connect-timeout-seconds: 15
  instance:
    preferIpAddress: true

  h2:
    console:
      enabled: false
      path: /h2