spring:
  jpa:
    properties:
      hibernate:
        session_factory:
          interceptor: com.semihunaldi.backendbootstrap.entitymodel.interceptor.EntityCommonFieldInterceptor
    open-in-view: true

eureka:
  client:
    enabled: true
