server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:mem:backendbootstrapdb
    url: jdbc:h2:tcp://localhost:9092/mem:backendbootstrapdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    schema: classpath:/db/sql/schema.sql
#    data: classpath:/db/sql/import.sql

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: none
              create-target: create.sql
    hibernate:
      ddl-auto: create
    generate-ddl: false

  data:
    mongodb:
#      authentication-database: admin
#      username: username
#      password: password
      database: backendbootstrapdb
      host: localhost
      port: 27017

  h2:
    console:
      enabled: true
      path: /h2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

app:
  properties:
    resourceId: ${RESOURCE_ID:backend-bootstrap-api}
    developerName: Semih Unaldi
    developerUrl: https://www.semihunaldi.com
    developerMail: semihunaldi@gmail.com
    authServer: http://localhost:8081
    clientId: curl_client
    clientSecret: password
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000