server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/semihunaldi/config-server-properties.git
          username: @bitbucket-git-username@
          password: @bitbucket-git-password@
  profiles:
    active: bitbucket-git

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true